# Generated by Django 4.2 on 2023-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productattachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
