# Generated by Django 4.2 on 2023-06-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productattachment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattachment',
            old_name='is_free',
            new_name='is_downloadable',
        ),
    ]
